### ISSUE TITLE
Location of log file

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#119]
Where is Qucs-S storing the ngspice error log file? Some files cause ngspice to crash and the on-screen messages disappear before they can be read. log.txt in the Qucs-S folder has no useful info.

When I use the DuSpice GUI for ngspice, the log and output files are stored in "C:\Ngspice-37_64\bin". 

This seems like a odd place to store files but it is what it is....

**Comment by ra3xdh** [comment]
The log file location is `$HOME/.qucs/spice4qucs/spice4qucs.log` Later it could be accessed by pressing F5 on keyboard or *Simulation->Show last messages* The netlist is `$HOME/.qucs/spice4qucs/spice4qucs.cir` (accessed by pressing F6).

But the Windows version has some unique features. The default Windows Ngspice build doesn't write the text log. It only shows it in the windows that is closed after the simulation is finished. You need to use `ngspice_con.exe` instead of `ngspice.exe` to see the text logs.
![image](https://user-images.githubusercontent.com/4920080/179366428-260b9996-a19e-4392-8f24-2dbebe3c250c.png)

**Comment by tomhajjar** [comment]
Shouldn't the "default" location be what is set in the "Qucs Home:" path? In my case I use .qucs - S not .qucs. I try to keep the two programs segregated from each other.  


![2022-07-16_184350](https://user-images.githubusercontent.com/102838604/179374075-dc303854-d491-4b6c-9221-44cc460ce4b9.jpg)

**Comment by ra3xdh** [comment]
Yes, I meant the "Qucs Home" path. Inside this directory is the default location for logs and netlist.

**Comment by tomhajjar** [comment]
Something is wrong then. The only spice4qucs directory is in my ".qucs" directory and the files generated by Qucs-S are there
![2022-07-17_084314](https://user-images.githubusercontent.com/102838604/179398925-8db982ed-50e3-4b92-82ec-ba666893dad5.jpg)
.

**Comment by ra3xdh** [comment]
Yes, I wrote a wrong location of the log file. It should be saved in Qucs home directory `log.txt`. The default is `$HOME/.qucs/log.txt` The correct log could be viewed by pressing F5 key. You can change the directory where the netlist and SPICE supplementary files are stored using the *Simulation->Select default simulator* dialog.
![image](https://user-images.githubusercontent.com/4920080/179399588-0ffe1ce8-d8a7-4448-ada2-c0e14966e84b.png)

**Comment by ra3xdh** [comment]
I have changed the default Ngspice executable name for Windows from `ngspice.exe` to `ngspice_con.exe` to avoid such issues with the log file in the future.
