### ISSUE TITLE
Subcircuit parameters support is broken?

### ISSUE THREAD

**Issue by denizzzka** [ra3xdh/qucs_s#131]
I am not sure this is my mistake or bug?

```
Ngspice started...
warning, can't find model 'rv' from line
    r1 _net0 _net1 rv
```
![image](https://user-images.githubusercontent.com/974632/183628804-b71c24d8-856d-4eb2-bb2b-403bb6fb16f3.png) ![image](https://user-images.githubusercontent.com/974632/183628916-6759a1d7-b3c9-4c9c-b67f-23bf2e2050f5.png)
![image](https://user-images.githubusercontent.com/974632/183628930-5eb9c849-afdb-4369-8687-663f9fc66b0d.png)

**Comment by ra3xdh** [comment]
I cannot reproduce your problem with Qucs-S+Ngspice-37. The circuit is simulated correctly on my machine. What Ngspice version are you using? Also try to wrap the variable in braces as shown. This will force Ngspice that this is variable but not model. Another solution is to use the blue resistors instead of red. For blue resistors Qucs-S wraps the value defined as variable in braces automatically. 
![image](https://user-images.githubusercontent.com/4920080/183634607-70b3ed3b-206b-4205-8f14-126af791f6e6.png)

**Comment by denizzzka** [comment]
ngspice-37 is used. Yes, circuit works with {} braces!

PS: Omg, here is three resistors types! :-)
