### ISSUE TITLE
Qucs/Qucs-S example repository

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#138]
Not sure your aware of this repository. It is used to teach college students. I found an issue with a BJT library the author uses extensively for the examples, bcmodels.lib. I contacted him but haven't received a response. The data in bcmodels.lib comes from On Semi and other vendors. When I use older libraries from Philips the issues disappear. I can use literally any NPN/PNP in the libraries and the circuit works. 

I cannot say if the problem is with the bcmodels.lib, Qucs-S or ngspice. 

https://github.com/saul-rodriguez/QUCS_ANALOG_ELEKTRONIK

[Oscillators_prj.zip](https://github.com/ra3xdh/qucs_s/files/9374840/Oscillators_prj.zip)

![2022-08-18_104304](https://user-images.githubusercontent.com/102838604/185423908-53d79f85-c3c5-4d14-b9a9-68e736939a25.jpg)
![2022-08-18_104346](https://user-images.githubusercontent.com/102838604/185423913-a9b9be5c-8dd5-4833-b32c-30f8836dfba0.jpg)

**Comment by ra3xdh** [comment]
I have tried the models from `BJT_Extended` library https://github.com/ra3xdh/qucs_s/blob/current/library/BJT_Extended.lib I obtained the correct result with these models. Something is wrong with models from `bcmodels.lib`. But I cannot figure out difference between two set models. I didn't find anything like unallowed characters etc. that can cause this issue. The question may be addressed to Ngspice help mailing list with providing a netlist and BJT models. Closing this ticket, because it is definitely not a Qucs-S issue.
