### ISSUE TITLE
New RF components

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#143]
Any chance more RF "stuff" from Qucs 0.0.20 might end up in the next release? INDQ, CAPQ? S-parameters?

![2022-08-25_100604](https://user-images.githubusercontent.com/102838604/186686765-4c2ca2dd-8e3a-44a8-a2c0-4438d2a0bfae.jpg)

**Comment by ra3xdh** [comment]
Yes, the INDQ and CAPQ devices are in my plan as the part of #94 I cannot say when exactly it will implemented in Qucs-S. The INDQ and CAPQ seem to easier as transmission lines. The s2p file device may have fundamental limitation that may make it incompatible with Ngspice. I am planning to start with INDQ and CAPQ and then continue with transmission lines.

**Comment by tomhajjar** [comment]
Do you need the source...

[qucs-0.0.20-rc2.zip](https://github.com/ra3xdh/qucs_s/files/9426615/qucs-0.0.20-rc2.zip)

**Comment by ra3xdh** [comment]
I can always take the Qt4 Qucs sources from Github https://github.com/Qucs/qucs The Qucs sources is a little help with implementation of the RF devices with Qucs-S+Ngspice. The S-parameter simulation works differently in Ngspice. The transmission line devices should be converted to LTRA device model https://ngspice.sourceforge.io/docs/ngspice-html-manual/manual.xhtml#magicparlabel-6082 The INDQ and CAPQ should be converted to subcircuits.

**Comment by tomhajjar** [comment]
The L/C "Q" models don't include resonance but are much better than nothing. 

Manufacturers resonance data doesn't take into account how the component is used and mounted onto the PCB so can be misleading. I measure inductors myself at operating frequency. Measurements rarely equal manufacturer data.

**Comment by rjordans** [comment]
selecting qucsator as the default simulator did allow me to use s2p files, but it's a bit annoying that I have to set this globally.  Would be nice if this could be set on a per-project basis

**Comment by ra3xdh** [comment]
@rjordans The setting of the simulator per project/schematic is not possible due to some architecture limitations of the GUI. The GUI doesn't support the reload of the components palette on the fly which is needed after the simulator has been changed. So, only the global setting of the simulator is possible.

**Comment by rjordans** [comment]
Ah, that's too bad then.  Thanks for the quick response!

**Comment by tomhajjar** [comment]
@ra3xdh

Presently Qucsactor is not included with Qucs-S. Is that going to change? If so will Qucsactor be updated to the latest revision?

**Comment by ra3xdh** [comment]
> Presently Qucsactor is not included with Qucs-S. Is that going to change?

No, Qucsator is maintained by another team https://github.com/qucs/qucsator and cannot be included in Qucs-S distribution. Qucsator team doesn't provide binary packages. But one can download and compile it manually if necessary.  Ngspice will remain the default simulator for Qucs-S, because Qucsator has numerous issues with TRAN simulation and SPICE models compatibility.

**Comment by tomhajjar** [comment]
I  used to get the latest Qucs Windows release but they stopped posting them 3 years ago. I have a very old release of Qucs 0.0.20.

I have asked many times for access to the latest Qucs 0.0.20 release but no one will provide it. They seem to be off on a new tangent based on Gnucsator. I then asked for it and was ignored.....

**Comment by ra3xdh** [comment]
I have just added INDQ and CAPQ devices. The attached screenshot illustrates its operation under Qucs-S+Ngspice. It should operate for AC, SP and TRAN analysis. These devices will be available since the next release v1.0.2.
![image](https://user-images.githubusercontent.com/4920080/222761875-6c77d349-f111-456c-bd9d-85b57e05747e.png)

**Comment by ra3xdh** [comment]
And here is INDQ device: 
![image](https://user-images.githubusercontent.com/4920080/222762743-32b2804f-2cd4-4443-9fb9-51a67e82d7d8.png)

**Comment by ra3xdh** [comment]
The attached screenshot shows a more complex example involving inductive coupling of INDQ devices.
![image](https://user-images.githubusercontent.com/4920080/222893574-d6eb74be-a0c6-4040-9233-8bb9692317ab.png)

**Comment by ra3xdh** [comment]
Closing this as resolved. New devices will be available since v1.0.2 release.
