### ISSUE TITLE
AnalogueCM.lib issues

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#152]
The AnalogueCM.lib library doesn't work. Some type of path issue

TODO list from @ra3xdh 

- [x] Fix logical operations conversion for Qucs legacy equations

**Comment by ra3xdh** [comment]
This library uses XSPICE code models and requires installed GCC compiler and make utility for operation. Otherwise it will not work. The `AnanlogueCM.lib` is only library using Code models. It is not a problem for Linux platform but may have some difficulties for Windows. Do you have MINGW and Make installed and available in `$PATH`?

**Comment by tomhajjar** [comment]
I believe I did a very long time ago on another PC. Not sure this library ever worked however. The library is not useful for me so it's not worthwhile trying make it work.

**Comment by tomhajjar** [comment]
I guess you can add the MESFETCL1 component in the MESFET library to the list

**Comment by tomhajjar** [comment]
![2022-09-17_174612](https://user-images.githubusercontent.com/102838604/190878100-f0126e29-7e21-4d96-94fb-7a20b34c8106.jpg)
![2022-09-17_181529](https://user-images.githubusercontent.com/102838604/190878105-175b6dd5-c203-4ca5-80e9-dde568b66530.jpg)
![2022-09-17_181332](https://user-images.githubusercontent.com/102838604/190878109-0d3bd9a1-05fa-4219-9cf3-d8394ef64c58.jpg)

[MESFET_Curtice_prj.zip](https://github.com/ra3xdh/qucs_s/files/9592686/MESFET_Curtice_prj.zip)

**Comment by ra3xdh** [comment]
Yes, there is a bug with Qucs equations support. The parser doesn't recognize the `V1` voltage near the `&&` logical operator and doesn't convert it to the SPICE syntax. As a workaround you may to wrap the condition in parentheses. 
![image](https://user-images.githubusercontent.com/4920080/190888871-fd64972a-3eef-4e0d-b86f-1d3ef366db7f.png)
After this correction is applied, the circuit could be simulated without error. Also the equation `Eqn1` should be deleted because it duplicates the current probe.

**Comment by ra3xdh** [comment]
I have added a fix for the EDD equations parser. Closing this.
