### ISSUE TITLE
Qucs-S "Equations" won't work for S-parameter analysis but do work for DC/AC and Transient analysis

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#157]
Qucs-S "Equations" won't work for S-parameter analysis using ngspice but DO work for DC/AC and Transient analysis using ngspice. 

Isn't Equations a "pre" and "post" operation so as long as there are limits on what can be in the equations, equations should work for S-parameter analysis using ngspice? 

This gets back to passing parameters and pre and post operations when doing S-parameters.

**Comment by ra3xdh** [comment]
The S-parameter simulation supports only Nutmeg equations. See `examples/ngspice/s_param_wideband_amp.sch` schematic. It contains example for VSWR computation. The legacy Qucs equations will not work with S-paramaters because of incompatible syntax. And I don't consider adding backward compatibility for these equations. If the Qucs equation contains only definition that should be computed before simulation it will work with Ngspice without problem.
