### ISSUE TITLE
Qucs-S not passing Resistor Tc1 or Tc2 to ngspice

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#193]
Qucs-S doesn't seem to pass Resistor Tc1 or Tc2 to ngspice.

Another issue is choosing the variable name for "Temperature" when doing a Temperature Sweep. Tsweep isn't accepted and Temp doesn't do anything. 
 
![2022-12-05_190452](https://user-images.githubusercontent.com/102838604/205773620-dad749c1-ad88-4012-a462-a4413c0c5eee.jpg)

![2022-12-05_190847](https://user-images.githubusercontent.com/102838604/205773627-309e9dce-bf6e-4b67-b276-05bf473451d5.jpg)

https://sourceforge.net/p/qucs/discussion/311050/thread/82256003/

[Rdiv_tsweep.zip](https://github.com/ra3xdh/qucs_s/files/10159168/Rdiv_tsweep.zip)

**Comment by ra3xdh** [comment]
Hello Tom, the Tc1 and Tc2 parameters of the blue resistors are ignored by Ngspice. Use red resistor instead. It allows to pass the full SPICE definition including model and temperature coefficients to the simulator. See the section 3.3.1 of the Ngspice manual for more details. The approach with `Tsweep` variable will not work with Qucs-S+Ngspice, because Ngspice cannot sweep variables. This will be improved after implementing of #189 in the upcoming v1.0.1 release. Use `TEMP` variable instead. It is a SPICE special global variable representing temperature.

**Comment by ra3xdh** [comment]
Look at the attached screenshot for simulation example:
![image](https://user-images.githubusercontent.com/4920080/205915693-da8dd298-6393-43a0-a9ae-264e24d84ba6.png)

**Comment by tomhajjar** [comment]
Should a comment be added to the device Description for devices that only pass parameters to Qucsator? 

![2023-01-16_093703](https://user-images.githubusercontent.com/102838604/212704112-d584e7d9-ffa6-48a4-a953-8fb6545cb9ed.jpg)
