### ISSUE TITLE
Crash in Voltage Probe

### ISSUE THREAD

**Issue by ivolovichev** [ra3xdh/qucs_s#253]
Reproducing issue:
1. Add "Voltage Probe" to new or existing schematic.
2. Open "Edit Component Properties" dialog.
3. Click on "display in schematic" checkbox.
Program crashes/terminates with the following output to stderr:
Fatal: ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/include/qt5/QtCore/qlist.h, line 539
Aborted
The issue is reproduced in Qucs-S-0-Build6.1.glibc2.14-x86_64.AppImage, Qucs-S-latest-x86_64.AppImage, and custom build from sources.

**Comment by ra3xdh** [comment]
Yes, I confirm this. The properties list for voltage and current probes is empty, and properties editing normally is not used for these devices. And this bug was unnoticed for years. I have added a fix for this on `current` branch. The fix will be available in the upcoming release. Closing ticket as resolved.

> The issue is reproduced in Qucs-S-0-Build6.1.glibc2.14-x86_64.AppImage, Qucs-S-latest-x86_64.AppImage

What is your distribution that you still need the AppImage? I am providing DEB/RPM packages and Arch also provides a package using AUR.
