### ISSUE TITLE
Possible issue, using MS windows pdf printer

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#284]
Hi, when printing with the MS windows pdf printer I can't get the text to stay in proportion to what I set in the .sch

![print_pdf_3](https://github.com/ra3xdh/qucs_s/assets/70080894/b97eaa34-39a8-4e41-88eb-9e755a6a3096)

**Comment by ra3xdh** [comment]
It looks like a bug in interaction of Qt itself and MS PDF printer. The PDF printing works as expected when using Linux. See the attached screenshot. This bug cannot be fixed because it depends on Qt itself. Use export to SVG (File->Export as image) instead of print to PDF. You can save SVG as PDF using inkscape later. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/dc7f5d99-6fa5-45f3-964c-85d65240ca63)
