### ISSUE TITLE
Built-in VCO from "Ideal" library is broken?

### ISSUE THREAD

**Issue by denizzzka** [ra3xdh/qucs_s#290]
Qucs-s 1.1.0:

![export](https://github.com/ra3xdh/qucs_s/assets/974632/7dcfb362-6efd-45aa-a4ce-ea4fcedd6c43)

```
Ngspice started...
warning, can't find model 'c' from line
    cc1 gnd _net1 c
Netlist line no. 0:
Undefined parameter [v1]
Netlist line no. 0:
Cannot compute substitute

ERROR: fatal error in ngspice, exit(1)

Note: No compatibility mode selected!


Circuit: * qucs 1.1.0 /home/denizzz/.qucs/test_bug_prj/vco_test.sch

Simulation finished
```

**Comment by ra3xdh** [comment]
Yes, I am aware about this problem. Furthermore this issue was already reported here #258 Some devices from `Ideal` library still be qucsator only. See my explanations in #258 There is no workaround to put these devices in operation. It's need to edit the library and provide SPICE entries for missing devices. I have planned the revision of the `Ideal` library, but I cannot promise to start this work till the next release.

**Comment by ra3xdh** [comment]
Closing this as duplicate. Use #258 to track the status of the `Ideal` library update.
