### ISSUE TITLE
Add low voltage for the rectangle sources

### ISSUE THREAD

**Issue by ljbade** [ra3xdh/qucs_s#310]
The rectangle voltage source doesn't provide a way to set the low voltage, only the high voltage.

I wanted a square wave with a negative low voltage. I think I can work around it by using another DC voltage source.

**Comment by ra3xdh** [comment]
I cannot change the existing source because all schematics containing it will be broken. You can use the full SPICE definition with arbitrary source (V-source) as the workaround. The example is shown below. See the Ngspice manual for description https://ngspice.sourceforge.io/docs/ngspice-html-manual/manual.xhtml#magicparlabel-4121
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/8ebbff57-13e5-4942-8c0c-13ead61a9b9e)

**Comment by ra3xdh** [comment]
I have added a fix for this. The backward compatibility of the square wave source should not be broken. Since the next version a new parameter `U0` representing the low voltage will be added. Qucsator doesn't support the low voltage of the square wave source, so this new parameter will be SPICE-only (supported by Ngspice/XYCE). Qucsator will ignore it and substitute zero. This fix will be available since the next release. Closing ticket as completed. 
 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/f8a38433-2a9f-403b-84d5-dae5f9cf5518)
