### ISSUE TITLE
Library Creation Issues

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#342]
I created a library called test.lib made up of two devices, a generic OpAmp and a delay element for ideal.lib. 

Component "Qucs-S Delay model" seems OK.

Component "genopa_sub" will not function if I don't send the model genericopa1.cir with the library. How do I make a self contained library independent of external files as pointed to by the following?

Test_genopa_sub.sch
.INCLUDE "C:/Users/Tom Hajjar/.qucs - S/Ideal Library Test_prj\genericopa1.cir"

[Test_Lib_prj.zip](https://github.com/ra3xdh/qucs_s/files/13194410/Test_Lib_prj.zip)

**Comment by ra3xdh** [comment]
This question was asked several times before. See also #140 You have to use `Spice netlist` device instead of `SpiceLibComp` if you are intending to create libraries from subcircuit. The purpose of SpiceLibComp is to use *unmodified* SPICE libraries with Qucs-S. That's why this device it still referencing external library.

**Comment by ra3xdh** [comment]
Assume the question about difference between *SPICE file* and *Spice Lib Comp* is closed.

**Comment by ra3xdh** [comment]
Closing this.
