### ISSUE TITLE
Modify SPICE RCLDQ devices to provide support for microelectronics PDKs

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#349]
I have recently added unified MOS devices that could be mapped to X letter. See #128 and #242. Other primitive devices also need to be modified to ensure compatibility with PDKs. It's need to add possibility to define pins number and letter. The following improvements should be done:

- [ ] Add terminal number and letter (C,X) property for capacitor  (needed 3-terminal capacitor)
- [ ] Add terminal number and letter (R,X) property for resistor (needed 3-terminal resistor)
- [ ] Define letter (D,X) and pins count for diode (needed 3-terminal diode)
- [x] Add terminal number and letter (Q,X,N) property for BJT

**Comment by Radvall** [comment]
I think more convenient way to use PDK in QUCS-S is to create a user library, rather than specifying the model name and model parameters for each element. I have no objection to such an approach, for a dozen elements it's OK. For a larger number, it seems to me that the library is better.

As an example of user library I am attaching a QUCS library for IHP-Open-PDK https://github.com/IHP-GmbH/IHP-Open-PDK. This library includes only resistors. The simulation are shown bellow:

![test_lib](https://github.com/ra3xdh/qucs_s/assets/60294840/a4d0c28b-ee2e-4fc3-a506-814f364ff668)

[IHP_Open_PDK_QUCS_S_user_test_lib.tar.gz](https://github.com/ra3xdh/qucs_s/files/13834499/IHP_Open_PDK_QUCS_S_user_test_lib.tar.gz)

**Comment by ra3xdh** [comment]
> I think more convenient way to use PDK in QUCS-S is to create a user library

Yes, I agreed with this. Furthermore we need to implement something like https://github.com/Qucs/qucs/issues/659 This will allow to put devices on the left panel without modifying C++ code.

**Comment by ra3xdh** [comment]
Closed via #431. I put new 3-pin devices into the new group called "Microelectronics"
