### ISSUE TITLE
QUCS-S 2.1.0: Tuner Slider Bug

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#406]
Problem:

The tuner slider parameters do not update accordingly in case the Max, Min, Val, Step field values have been changed.
The slider parameters are not fully consistent with the parameter fields.

Problem demo:

<<Tuner_Slider_Bug_Video.zip>>
<<HBM_9_prj.zip>>

Potential solution for correction:

If any  Max, Min, Val, Step field values have been changed: update all tuner slider parameters, including Val, if Val is outside the Min to Max range. Val should be assigned to the closer side Min or Max then. 

[HBM_9_prj.zip](https://github.com/ra3xdh/qucs_s/files/13763461/HBM_9_prj.zip)
[Tuner_Slider_Bug_Video.zip](https://github.com/ra3xdh/qucs_s/files/13763463/Tuner_Slider_Bug_Video.zip)

**Comment by ra3xdh** [comment]
This bug was fixed by https://github.com/ra3xdh/qucs_s/commit/d0b6e74a7aa76ea72cff5e7b8b0800f15430ba5a Here is the screencast illustrating how it looks in the version from Git. The fix will be available since the next release.
![Peek 2023-12-25 11-10](https://github.com/ra3xdh/qucs_s/assets/4920080/de71ebf5-c5d6-4032-aca1-006181a9023a)

**Comment by ra3xdh** [comment]
Closing as completed. Fixed on `current` branch.
