### ISSUE TITLE
Phantom wires while moving seleted components by mouse or arrow keys

### ISSUE THREAD

**Issue by zergud** [ra3xdh/qucs_s#468]
wire and node appears instead of reduce wire length
length of phantom wire equals movement distance - dx for horizontal, dy for vertical

![image](https://github.com/ra3xdh/qucs_s/assets/869819/3191750d-e046-49a1-9dbd-57438f0a59fb)

**Comment by zergud** [comment]
@wawuwo this bug may be intresting for you, while you plunged into the depths of schematic )
it appear while wire segment moving in wire bend direction

for example - if we move such selection UP

![image](https://github.com/ra3xdh/qucs_s/assets/869819/1f5f87dd-75c6-4493-9c71-cff8ee63d802)

**Comment by wawuwo** [comment]
@zergud that's an interesting case, I'd call the bug what happens when you move selected components down :)

I mean, having selected a _whole_ wire, you expect it move as a whole, as one piece. And after such move, it lies on a node and automatically connected with it, creating two wires. The result is logically equivalent to the picture on the right side:
<img width="700" alt="image" src="https://github.com/ra3xdh/qucs_s/assets/40355531/d437d1b8-0b59-476d-a004-9369993611a7">

So every move up after the first one is actually an attempt to lay one wire on top of another and overlapping segment is optimised away, that's why it doesn't grow further up. This looks perfectly reasonable.

But! When you move the whole wire _down_, it is extended, but not moved down as one piece as one would think. 
But! We can look at this "extension" like this: at first the wire is moved down as one piece and to keep connected to the node a short wire is inserted. And then these two wires are optimised into one wire.

**Comment by zergud** [comment]
I already broke my head once and decided to take a break ))
try to turnoff snap to grid and move... nice picture )

but "the truth is somewhere near"

**Comment by ra3xdh** [comment]
> I already broke my head once and decided to take a break ))

The wires with one hanging end don't affect the simulation. This issue may be left as is if not possible to fix. The bug was presented since Qt4 version.

**Comment by zergud** [comment]
> try to turnoff snap to grid and move
ups, i mean "move with ctrl pressed"

>The bug was presented since Qt4 version.
this doesn't mean that we don't have to fix it ))

**Comment by wawuwo** [comment]
@zergud
>ups, i mean "move with ctrl pressed"

I still can't get what is the bug you mean :( Here I move a wire with the Ctrl pressed:
![4](https://github.com/ra3xdh/qucs_s/assets/40355531/66e26852-8468-44b9-906d-f807d3e2de7e)

Is it possible for you to record a video?

**Comment by zergud** [comment]
hmmm... I can't repeat ))
many phantom pins appears while moving without snap to grid
probably it fixed by #509 or elsewhere )

**Comment by wawuwo** [comment]
@zergud, shouldn't we close the issue or maybe mark it as "backlog" or something? I mean no one managed to reproduce the issue…

**Comment by zergud** [comment]
![phantom-net](https://github.com/ra3xdh/qucs_s/assets/869819/0ad5e6c4-0cee-44b0-abda-f04bfc4ce934)

**Comment by wawuwo** [comment]
>do you have Windows PC?

Unfortunately no, I don't.

Regarding the example you've provided: I finally see what you consider a bug, but I can't get why it is a bug for you :) I mean let's take this example:

https://github.com/ra3xdh/qucs_s/assets/40355531/185a0209-db01-4b72-b5cb-8d62e77ddcde

It looks to me like absolutely reasonable and expected behaviour: the whole wire is selected, moved as _one piece_ and placed at new location. In your example the same action is performed but with a set of components instead, not a wire alone…

**Comment by zergud** [comment]
if you select many wires then you can get a lot of unconnected nodes
it seems I'm the only one who has problems with this behavior 
lets close issue and forget
thanx )
