### ISSUE TITLE
windows height

### ISSUE THREAD

**Issue by dwarning** [ra3xdh/qucs_s#587]
Compiling latest current branch on Ubuntu 22.04 (old laptop) follows in very large heights for all simulation windows. This was not the case in previous builds:
![Bildschirmfoto vom 2024-02-18 14-42-58](https://github.com/ra3xdh/qucs_s/assets/18441932/4bda8229-7ee1-4a3a-a935-5b2f4c179618)

**Comment by iwbnwif** [comment]
From the greying of the main window it looks like "Attach Modal Dialogs" might be selected in Gnome. It still doesn't explain the resizing, but it may be a side effect.

If you have Gnome Tweaks installed, you can try disabling it there under "Windows".

**Comment by dwarning** [comment]
I tried this Gnome setting configuration - but no change. The dialog boxes have still maximum height.
Behaviour has changed since 24.0.

**Comment by ra3xdh** [comment]
I never observed this issue using KDE+X11 or Windows. I changed nothing related to dialog size policy.

**Comment by iwbnwif** [comment]
Did you try to resize the window? The simulation window size is now retained from the previous time since #529. 

I am using Ubuntu 22.04 and don't see this problem, but it may be that if Attach Modal Dialogs setting is active, then the initial (default with no configuration in the settings file) may somehow set the height to maximum. 

I will look into it a bit later, but in the meantime please can you try adjusting the size and seeing if it is retained between components.

**Comment by dwarning** [comment]
Yes - it is the retaining effect. I can resize, close the program, reopen and see same size as before.
Sorry, I never noticed this feature before.
Thank you - I will close.
