### ISSUE TITLE
Issues RC Transient Simulation

### ISSUE THREAD

**Issue by jgardona** [ra3xdh/qucs_s#638]
This simple rc circuit transient simulation cant generate capacitor curve.

Add 0v to capacitor and 1000 points for simulation. Capacitor is not draining resistor current or voltage.

![image](https://github.com/ra3xdh/qucs_s/assets/146892539/ea61055b-f39c-4e52-9168-75d820863000)

[rctrans.zip](https://github.com/ra3xdh/qucs_s/files/14548232/rctrans.zip)

**Comment by tomhajjar** [comment]
V1 doesn't change. How would you see the capacitor charge or discharge? 

Use a step.

![2024-03-09_232431](https://github.com/ra3xdh/qucs_s/assets/102838604/18db0fc6-c07a-4871-99ce-7b2ab2c947cb)

**Comment by ra3xdh** [comment]
Everything is correct. As I guess, you are trying to apply initial conditions. Ngspice doesn't apply IC automatically. This question was asked and answered several times before: https://github.com/ra3xdh/qucs_s/issues/291 https://github.com/ra3xdh/qucs_s/issues/226 https://github.com/ra3xdh/qucs_s/discussions/317 This requires to set option `InitialDC=no` for TRAN simulation. I don't know how to make this option more visible, because users don't read the description.

**Comment by jgardona** [comment]
> Everything is correct. As I guess, you are trying to apply initial conditions. Ngspice doesn't apply IC automatically. This question was asked and answered several times before: #291 #226 #317 This requires to set option `InitialDC=no` for TRAN simulation. I don't know how to make this option more visible, because users don't read the description.

You are right. Here is the result. In Ltspice I think this is managed under the hood.
![image](https://github.com/ra3xdh/qucs_s/assets/146892539/2b55d97b-bf94-4c11-b28a-98023043bc56)
