### ISSUE TITLE
Matching Circuit Tool generates wrong results

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#905]
Update: 

The device seems to be marginally stable.
Project updated with all fixes

Follow up to #401, @andresmmera

In testing Matching Circuit Tool for an "L-section match" case, I found the component values to be unrealistic. 

The input match L1 shunt inductor value of "0.000H" should be interpreted as a short to ground or possibly using "creative license", an open circuit to ground. The output match L4 series inductor value of "2.556H" can only be interpreted as an open circuit.

I didn't test any other cases since having to copy and paste S-parameter values becomes tedious and error prone.

![2024-08-23_184159](https://github.com/user-attachments/assets/3b0bd9ec-73d0-49d8-bca8-3d950cad60e9)
![2024-08-23_184019](https://github.com/user-attachments/assets/fd55dba1-162b-4acf-b52b-e2f0748bf8bb)
![2024-08-23_183704](https://github.com/user-attachments/assets/56aebefd-2680-4629-bc2c-9fffbd491cf4)

[BFP193W_amplifier_prj.zip](https://github.com/user-attachments/files/16737223/BFP193W_amplifier_prj.zip)

**Comment by andresmmera** [comment]
Hi @tomhajjar , thanks for pointing this out.

The device is not unconditionally stable and it cannot be conjugately matched. Equations 12.40a/b in [1] don't have a solution for this case since the argument of the square roots is negative.

![image](https://github.com/user-attachments/assets/ed93bb27-91d1-4078-b867-46e7d58b7d6c)

![image](https://github.com/user-attachments/assets/7f548612-48b4-4dfd-bbb5-b228842b1556)

I think that the best solution would be to check if the device is unconditionally stable [here](https://github.com/ra3xdh/qucs_s/blob/current/qucs/dialogs/matchdialog.cpp#L976) in order to avoid wrong results like this. I can write a fix for this later.

Schematic: 
[BFP193W_spar_analysis.zip](https://github.com/user-attachments/files/16735773/BFP193W_spar_analysis.zip)

[1] Microwave Engineering. David M Pozar. 4th Edition. 2012

**Comment by tomhajjar** [comment]
Not often a device's Spice model correlates so well with it's S-parameter data...

![2024-08-24_085057](https://github.com/user-attachments/assets/54d4b3f2-c573-47e3-acc2-c27fab906e24)
![2024-08-24_085112](https://github.com/user-attachments/assets/0f5e0201-b24f-4de0-8de2-d3f30327821e)

**Comment by tomhajjar** [comment]
@andresmmera

One minor issue with the tool is if any entry or setting is "wrong" or out of bounds, a error message is shown and the tool is closed. Is there a way to allow the user to fix the wrong entry and not close the tool?

**Comment by andresmmera** [comment]
Good point. I'll take a look later.

**Comment by ra3xdh** [comment]
Fixed by #907. Closing as completed.

**Comment by andresmmera** [comment]
> @andresmmera
> 
> One minor issue with the tool is if any entry or setting is "wrong" or out of bounds, a error message is shown and the tool is closed. Is there a way to allow the user to fix the wrong entry and not close the tool?

Fixed in PR #909

**Comment by tomhajjar** [comment]
This Qorvo tool is useful for seeing the effect of R on K.

![2024-08-25_130123](https://github.com/user-attachments/assets/be17e0af-71ec-4fb9-8bf6-cd3352a537f7)
