### ISSUE TITLE
Fix MOSFET symbol zooming

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#93]
Qucs-S and Qucs is using the symbol for depletion mode MOSFET when placing an enhancement mode MOSFET onto the schematic. The symbol is correct in the left component or library panel and is correct when dragging the component onto the schematic BUT when you click the mouse the wrong symbol is placed. Doesn't matter if it is the n, p or version with substrate. It always places the depletion version of the device.

![2022-06-10_161222](https://user-images.githubusercontent.com/102838604/173144610-accfa3a2-d75a-44ad-935d-363d6789bee9.jpg)

**Comment by tomhajjar** [comment]
Sorry I put Qucs first. Attached is Qucs-S doing same thing. 

![2022-06-10_162413](https://user-images.githubusercontent.com/102838604/173145178-e9d723b9-f81f-42b1-9e93-a54ee7cc02a9.jpg)
g

**Comment by ra3xdh** [comment]
Yes, the MOSFET library was inherited from Qucs and the behavior will be the same. It seems that the default symbol in the library is wrong.

**Comment by ra3xdh** [comment]
I performed a more investigations on this issue. The default symbol in the library is correct and usual MOSFET is also affected. The origin of this issue is related to the way how Qt processes the line thickness scaling. If you will zoom in the schematic, you will see the correct symbol. The Qucs uses a custom widget to render the schematic. If the schematic would be ported to QGraphicsScene, it probably would to fix this issue. Another way is to fix the MOSFET symbol in `mosfet.cpp`
![image](https://user-images.githubusercontent.com/4920080/173177093-ffe91a5a-b121-4764-a978-72178a2038ec.png)

**Comment by tomhajjar** [comment]
I understand. Still odd the symbols look OK in the left panel menus and when dragging onto the schematic. They look wrong once placed.

**Comment by ra3xdh** [comment]
Left panel uses pre-rendered PNG icons and therefore doesn't depend on Qt scaling. The symbol outline is rendered using line width=1 while dragging. The final symbol view uses thick lines that cause Qt rendering issues.

**Comment by tomhajjar** [comment]
Is there a reason the choices for MOSFET symbols is so limited? There isn't a choice for enhancement mode devices. It makes schematics look odd when you have to choose the symbol for a depletion mode device with substrate for a common power MOSFET. I realize there is the Qucs legacy choices but they don't make it easy to enter Spice parameters.
 
![2022-06-11_154154](https://user-images.githubusercontent.com/102838604/173202581-f3a2baac-bdcd-4fcd-bdb8-a0907841b253.jpg)

**Comment by ra3xdh** [comment]
I cannot say why the SPICE MOSFET symbols (dark red) were designed as depletion mode MOSFET. Probably it was simpler to draw one line instead of three lines. Concerning the parameters input, you may enter the model in the `Line_2`, `Line_3` parameters and use continuation line with `+` sign. Also you can put the model file to the `$HOME/.qucs/user_lib` directory and then drag'n'drop the model using the library manager. The `.MODEL` component will be created automatically in a such case. You need to reference it in the SPICE device.

**Comment by ra3xdh** [comment]
I have fixed MOSFET symbols look. The fix will be available since v1.0.2 release. 
![image](https://user-images.githubusercontent.com/4920080/218395705-744bc0ef-a834-4a77-95e1-81643b19f21f.png)
